export const CREATORS = [
  {
    id: "athlete-1",
    name: "Sarah Martinez",
    sport: "Tennis",
    type: "athlete" as const,
    avatar: "/placeholder.svg?height=80&width=80",
    coverImage: "/placeholder.svg?height=200&width=400",
    followers: "15.2K",
    following: "892",
    rating: 4.9,
    specialty: "Serve Technique",
    bio: "Professional tennis player specializing in serve technique and mental game. NCAA Champion with 8+ years of competitive experience.",
    location: "California, USA",
    university: "Stanford University",
    achievements: ["NCAA Champion 2022", "Regional Tournament Winner", "All-American 2021"],
    isVerified: true,
    subscriptionPrice: 29.99,
    responseRate: "98%",
    totalStudents: 127,
    experience: "8+ years",
    joinedDate: "2022-01-15",
    totalPosts: 234,
    totalVideos: 89,
    avgSessionLength: "45 min",
    languages: ["English", "Spanish"],
    certifications: ["USPTA Certified", "Mental Performance Coach"],
    socialMedia: {
      instagram: "@sarahtennis",
      twitter: "@sarahm_tennis",
      youtube: "SarahTennisCoach",
    },
    recentActivity: [
      {
        type: "video",
        title: "Advanced Serve Technique Breakdown",
        timestamp: "2 hours ago",
        likes: 234,
        comments: 45,
      },
      {
        type: "post",
        title: "Mental preparation before big matches",
        timestamp: "1 day ago",
        likes: 156,
        comments: 23,
      },
    ],
    stats: {
      totalLessons: 156,
      avgRating: 4.9,
      completionRate: "94%",
      studentSatisfaction: "98%",
      totalContent: 156,
      totalViews: "2.3M",
    },
  },
  // ... (repeat for all other athletes/coaches/mentors from MOCK_ATHLETES) ...
]; 